apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Bare-metal cluster (amd64). Runs two replicas.
resources:
- ../../base
patches:
- path: replicas-patch.yaml
images:
- name: ghcr.io/jmansmann/hello-mantooth
  newName: ghcr.io/jmansmann/hello-mantooth
  newTag: sha-5289d1b40c5fba7204c3b7c0cb6ce7b463198510
