apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Bare-metal cluster (amd64). Runs two replicas.
resources:
  - ../../base
patches:
  - path: replicas-patch.yaml
images:
  - name: ghcr.io/jmansmann/hello-mantooth
    newName: ghcr.io/jmansmann/hello-mantooth
    newTag: sha-b523683a04d36fe6a2fdda708369d3de98ed0b0f
